# Start window and pane numbering from 1 for easier switching
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is removed.
set -g renumber-windows on

# Allow the mouse to resize windows and select tabs
set -g mouse on

# Improve colors
set -g default-terminal "${TERM}"
set -as terminal-features ",*:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"

# 'PREFIX r' to reload of the config file
unbind r
bind r source-file ~/.tmux.conf\; display-message '~/.tmux.conf reloaded'
